title = "Mystical Rose School of Caloocan"
baseURL = "https://www.mysticalroseschoolofcaloocan.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  site_logo = ""
  description = "A private school in Camarin, North Caloocan"
  facebook = "https://www.facebook.com/mrsciofficial/"
  twitter = "https://www.facebook.com/Mystical_OSA25-1979746802340645/"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCpZUF9ShbeVxXtkE9FFV4_Q"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "https://graizoah.com/afu.php?zoneid=3358676"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  featured_image = "/images/mystical-facade.jpg"
  recent_posts_number = 2