title = "Mystical Rose School of Caloocan"
baseURL = "https://www.mysticalroseschoolofcaloocan.com"
theme = "ananke"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 10

[languages.en]
contentDir = "content"
languageCode = 'en-US'
weight = 1
title = "Mystical Rose School of Caloocan"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["post"]
text_color = ""
author = "MRSCI"
favicon = "favicon.ico"
site_logo = ""
description = "A private school in Camarin, North Caloocan, Philippines"
background_color_class = "bg-dark-blue"
featured_image_class = "cover bg-top"
cover_dimming_class = "bg-black-60"
recent_posts_number = 10

[params.ananke.social.share]
networks = [
  "facebook",
  "youtube"
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "youtube"
]

[params.ananke.social.facebook]
username = "mrsciofficial"

[params.ananke.social.youtube]
username = "MRSCIMEDIACHANNEL2018"