title = "Mystical Rose School of Caloocan"
baseURL = "https://www.mysticalroseschoolofcaloocan.com"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  site_logo = ""
  description = "A private school in Camarin, North Caloocan, Philippines"
  facebook = "https://www.facebook.com/mrsciofficial/"
  twitter = "https://www.facebook.com/osapagelive/"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UC2LINhbeAwuo93LO-VUlpyg"
  github = "https://github.com/AnimMouse/mystical-rose-website"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "https://graizoah.com/afu.php?zoneid=3358676"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  featured_image = "/images/mystical-facade.jpg"
  recent_posts_number = 5