name: Deploy Hugo Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Website
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
        
      - name: Build Hugo
        run: HUGO_ENV=production hugo # HUGO_ENV is required by Ananke for production

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: www.mysticalroseschoolofcaloocan.com