name: Hugo Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Website
        uses: actions/checkout@latest
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@latest
        with:
          hugo-version: 'latest'
        
      - name: Build Hugo
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: www.mysticalroseschoolofcaloocan.com